version: 0.0
os: linux	
files:	
  - source: 
    destination: /var/www/html/	    
hooks:	
  BeforeInstall:	 
    - location: scripts/beforeinstall.sh
      timeout: 300	     
      runas: ubuntu	     
    - location: scripts/afterinstall.sh  
      timeout: 300	     
      runas: ubuntu
